// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define ID_CMD_NEW 2 
#define ID_CMD_NEW_LabelTitle_RESID 60001
#define ID_CMD_NEW_LabelDescription_RESID 60002
#define ID_CMD_NEW_TooltipTitle_RESID 60003
#define ID_CMD_NEW_TooltipDescription_RESID 60004
#define ID_CMD_NEW_LargeImages_RESID 60005
#define ID_CMD_OPEN_BINARY 3 
#define ID_CMD_OPEN_BINARY_LabelTitle_RESID 60006
#define ID_CMD_OPEN_BINARY_LabelDescription_RESID 60007
#define ID_CMD_OPEN_BINARY_TooltipTitle_RESID 60008
#define ID_CMD_OPEN_BINARY_TooltipDescription_RESID 60009
#define ID_CMD_OPEN_BINARY_LargeImages_RESID 60010
#define ID_CMD_OPEN_BITMAP 4 
#define ID_CMD_OPEN_BITMAP_LabelTitle_RESID 60011
#define ID_CMD_OPEN_BITMAP_LabelDescription_RESID 60012
#define ID_CMD_OPEN_BITMAP_TooltipTitle_RESID 60013
#define ID_CMD_OPEN_BITMAP_TooltipDescription_RESID 60014
#define ID_CMD_OPEN_BITMAP_LargeImages_RESID 60015
#define ID_CMD_SAVE_BINARY 5 
#define ID_CMD_SAVE_BINARY_LabelTitle_RESID 60016
#define ID_CMD_SAVE_BINARY_LabelDescription_RESID 60017
#define ID_CMD_SAVE_BINARY_TooltipTitle_RESID 60018
#define ID_CMD_SAVE_BINARY_TooltipDescription_RESID 60019
#define ID_CMD_SAVE_BINARY_LargeImages_RESID 60020
#define ID_CMD_SAVE_BITMAP 6 
#define ID_CMD_SAVE_BITMAP_LabelTitle_RESID 60021
#define ID_CMD_SAVE_BITMAP_LabelDescription_RESID 60022
#define ID_CMD_SAVE_BITMAP_TooltipTitle_RESID 60023
#define ID_CMD_SAVE_BITMAP_TooltipDescription_RESID 60024
#define ID_CMD_SAVE_BITMAP_LargeImages_RESID 60025
#define ID_CMD_EXIT 7 
#define ID_CMD_EXIT_LabelTitle_RESID 60026
#define ID_CMD_EXIT_LabelDescription_RESID 60027
#define ID_CMD_EXIT_TooltipTitle_RESID 60028
#define ID_CMD_EXIT_TooltipDescription_RESID 60029
#define ID_CMD_EXIT_LargeImages_RESID 60030
#define ID_CMD_DRAW_LINE 8 
#define ID_CMD_DRAW_LINE_LabelTitle_RESID 60031
#define ID_CMD_DRAW_LINE_LabelDescription_RESID 60032
#define ID_CMD_DRAW_LINE_LargeImages_RESID 60033
#define ID_CMD_DRAW_RECTANGLE 9 
#define ID_CMD_DRAW_RECTANGLE_LabelTitle_RESID 60034
#define ID_CMD_DRAW_RECTANGLE_LabelDescription_RESID 60035
#define ID_CMD_DRAW_RECTANGLE_LargeImages_RESID 60036
#define ID_CMD_DRAW_ELLIPSE 10 
#define ID_CMD_DRAW_ELLIPSE_LabelTitle_RESID 60037
#define ID_CMD_DRAW_ELLIPSE_LabelDescription_RESID 60038
#define ID_CMD_DRAW_ELLIPSE_LargeImages_RESID 60039
#define ID_CMD_DRAW_CURVE 11 
#define ID_CMD_DRAW_CURVE_LabelTitle_RESID 60040
#define ID_CMD_DRAW_CURVE_LabelDescription_RESID 60041
#define ID_CMD_DRAW_CURVE_LargeImages_RESID 60042
#define ID_CMD_TAB_MAIN 12 
#define ID_CMD_TAB_MAIN_LabelTitle_RESID 60043
#define ID_CMD_GROUP_SHAPE 13 
#define ID_CMD_GROUP_SHAPE_LabelTitle_RESID 60044
#define ID_CMD_GROUP_COLOR 14 
#define ID_CMD_GROUP_COLOR_LabelTitle_RESID 60045
#define ID_CMD_DROPDOWN_SIZE 15 
#define ID_CMD_DROPDOWN_SIZE_LabelTitle_RESID 60046
#define ID_CMD_DROPDOWN_SIZE_LargeImages_RESID 60047
#define ID_CMD_DROPDOWN_STYLE 16 
#define ID_CMD_DROPDOWN_STYLE_LabelTitle_RESID 60048
#define ID_CMD_DROPDOWN_STYLE_LargeImages_RESID 60049
#define ID_CMD_COLOR_RED 17 
#define ID_CMD_COLOR_RED_LargeImages_RESID 60050
#define ID_CMD_COLOR_YELLOW 18 
#define ID_CMD_COLOR_YELLOW_LargeImages_RESID 60051
#define ID_CMD_COLOR_BLACK 19 
#define ID_CMD_COLOR_BLACK_LargeImages_RESID 60052
#define ID_CMD_COLOR_BLUE 20 
#define ID_CMD_COLOR_BLUE_LargeImages_RESID 60053
#define ID_CMD_COLOR_EDIT_COLOR 21 
#define ID_CMD_COLOR_EDIT_COLOR_LabelTitle_RESID 60054
#define ID_CMD_COLOR_EDIT_COLOR_LargeImages_RESID 60055
#define ID_CMD_GROUP_SIZE 22 
#define ID_CMD_GROUP_SIZE_LabelTitle_RESID 60056
#define ID_CMD_GROUP_STYLE 23 
#define ID_CMD_GROUP_STYLE_LabelTitle_RESID 60057
#define InternalCmd2_LabelTitle_RESID 60058
